spring.application.name=users-ws
server.port=${PORT:0}
eureka.client.service-url.defaultZone=http://localhost:8010/eureka
spring.devtools.restart.enabled=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.datasource.username=sa
#spring.datasource.password=sa

#gateway.ip=127.0.0.1
token.expiration_time=3600000
token.secret_key=hHUwRhWMVLp9oW1XUie5aFuxFXbvXYHqgQqX0PZlwkbwT1vmWE1GdpmrLdi7emmj
login.url.path=/users/login
logging.level.org.springframework.security:TRACE
spring.config.import=optional:configserver:http://localhost:8012
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest