spring.application.name=users-ws
server.port=${PORT:0}
eureka.client.service-url.defaultZone=http://localhost:8010/eureka
spring.devtools.restart.enabled=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.datasource.username=sa
#spring.datasource.password=sa

#gateway.ip=127.0.0.1
token.expiration_time=3600000
token.secret_key=hHUwRhWMVLp9oW1XUie5aFuxFXbvXYHqgQqX0PZlwkbwT1vmWE1GdpmrLdi7emmj
login.url.path=/users/login
spring.config.import=optional:configserver:http://localhost:8012
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
logging.level.com.example.photoapp.users.data=DEBUG
management.endpoints.web.exposure.include=health,mappings,info,busrefresh,busenv,circuitbreakerevents
management.endpoints.health.enabled=true
management.endpoints.health.show-details=true
management.health.circuitbreakers.enabled=true
management.endpoint.circuitbreakerevents.enabled=true
resilience4j.circuitbreaker.circuitBreakerAspectOrder=1
resilience4j.circuitbreaker.instances.albums-ws.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.albums-ws.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.albums-ws.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.albums-ws.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.albums-ws.sliding-window-size=2
resilience4j.circuitbreaker.instances.albums-ws.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.albums-ws.event-consumer-buffer-size=3
resilience4j.retry.retryAspectOrder=2
resilience4j.retry.instances.albums-ws.max-attempts=3
resilience4j.retry.instances.albums-ws.wait-duration=2s
resilience4j.retry.instances.albums-ws.enable-exponential-backoff=true
resilience4j.retry.instances.albums-ws.exponential-backoff-multiplier=5
