spring.application.name=accounts-ws
server.port=0
eureka.client.service-url.defaultZone=http://localhost:8010/eureka
spring.devtools.restart.enabled=true
eureka.instance.prefer-ip-address=true
spring.config.import=optional:configserver:http://localhost:8012
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
token.secret_key=hHUwRhWMVLp9oW1XUie5aFuxFXbvXYHqgQqX0PZlwkbwT1vmWE1GdpmrLdi7emmj